# Generated by Django 4.1.3 on 2023-01-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ammo',
            fields=[
                ('uiIndex', models.IntegerField(primary_key=True, serialize=False)),
                ('AmmoCaliber', models.CharField(max_length=100)),
                ('BRCaliber', models.CharField(max_length=100)),
            ],
        ),
    ]
